proyecto\frontendBundle\Entity\Columna:
    type: entity
    table: columna
    indexes:
        id_informe:
            columns:
                - id_informe
        id_subpregunta:
            columns:
                - id_subpregunta
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreColumna:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: nombre_columna
        tratamiento:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        grafica:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: Grafica
    manyToOne:
        idInforme:
            targetEntity: Informe
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_informe:
                    referencedColumnName: id
            orphanRemoval: false
        idSubpregunta:
            targetEntity: Subpregunta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_subpregunta:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
