proyecto\frontendBundle\Entity\DatosAsociados:
    type: entity
    table: datos_asociados
    indexes:
        id_participante:
            columns:
                - id_participante
        datos_asociados_ibfk_1:
            columns:
                - id_fragmento
        id_pregunta:
            columns:
                - id_pregunta
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idFragmento:
            targetEntity: Fragmento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_fragmento:
                    referencedColumnName: id
            orphanRemoval: false
        idParticipante:
            targetEntity: Participante
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_participante:
                    referencedColumnName: id
            orphanRemoval: false
        idPregunta:
            targetEntity: Pregunta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_pregunta:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
