proyecto\frontendBundle\Entity\Estudio:
    type: entity
    table: estudio
    uniqueConstraints:
        nombre:
            columns:
                - nombre
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        numSecciones:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: num_secciones
        numDatosEstudio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: num_datos_estudio
        descripcion:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        activa:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
