proyecto\frontendBundle\Entity\PantallaBienvenida:
    type: entity
    table: pantalla_bienvenida
    indexes:
        id_parte_estudio:
            columns:
                - id_parte_estudio
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mensaje:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        idParteEstudio:
            targetEntity: ParteEstudio
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_parte_estudio:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
