proyecto\frontendBundle\Entity\Participante:
    type: entity
    table: participante
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
