proyecto\frontendBundle\Entity\TiempoRespuesta:
    type: entity
    table: tiempo_respuesta
    indexes:
        id_participante:
            columns:
                - id_participante
        id_pregunta:
            columns:
                - id_pregunta
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tiempoRespuesta:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: tiempo_respuesta
    manyToOne:
        idParticipante:
            targetEntity: Participante
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_participante:
                    referencedColumnName: id
            orphanRemoval: false
        idPregunta:
            targetEntity: Pregunta
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_pregunta:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
