proyecto\frontendBundle\Entity\Usuario:
    type: entity
    table: usuario
    indexes:
        rol:
            columns:
                - rol
    uniqueConstraints:
        nombre:
            columns:
                - nombre
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        contrasena:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
    manyToOne:
        rol:
            targetEntity: Rol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rol:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
