proyecto\backendBundle\Entity\TipoPregunta:
    type: entity
    table: tipo_pregunta
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
