parameters:
#    proyectofrontend.example.class: proyecto\frontendBundle\Example

services:
#    proyectofrontend.example:
#        class: %proyectofrontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
